### ISSUE TITLE
Smaller fonts for mod books is very hard to read

### ISSUE THREAD

**Issue by penguinsane** [John-Smith-Modded/JSTR-1.7.x#51] opened 2015-01-15 22:23 UTC
Some mods add books, which sort of narrows the font and makes it very hard to read. Changing resolutions and fullscreening does not help, all looks the same.

Just figured I'd suggest it, here's some examples:

Thaumcraft Thaumonomicon: http://puu.sh/ezi5v/3dab1c2bd0.jpg
Botania index: http://puu.sh/eziat/63d4983e6d.png
Botania page: http://puu.sh/ezigt/25e9625103.png

**Comment by JokerReaper** [comment] 2015-01-24 14:34
i think the problem lies within the font itself, i looked up the site that was given in the read me file "http://typodermicfonts.com/berylium-font-spruced-up/" & it says there has been some graphical glitches & it explains that the font was too light & too low in some accents. maybe updating the font will fix this issue. if it has been updated already, then im out of ideas

**Comment by Oddface** [comment] 2015-01-24 17:23
We really should consider changing the font for JSTR. I do like the font, but it just doesn't work with the small text in the mod books, and books are kind of important in modded Minecraft these days. I don't know what a good replacement would be, just something with less thin lines, I guess?

**Comment by ScottKillen** [comment] 2015-01-24 17:28
Perhaps break the font out into an override pack for purists and let the font default to vanilla. I have to strip out the font manually from the pack.

**Comment by Glowstrontium** [comment] 2015-01-24 17:31
Most texture packs just use a higher-res default font, I'd expect the reason for this is exactly this - on top of the long standing issue of not being able to change the colour (without using hackish methods).  I just wish MC would switch over to True-type fonts to fix all of this once and for all.

**Comment by ScottKillen** [comment] 2015-01-24 17:36
Indeed. And there was a BetterFont mod once that did just that...but it is no more. :frowning:

**Comment by JokerReaper** [comment] 2015-01-24 17:37
idk if that'll happen being that microsoft has taken ownership of the game development, they seem to be trying to make it harder to mod the game by adding some lines of code, but that might be here say, but i have noticed that the ability to run your own server is getting more difficult because no one has fixed the user interface for the server, its all screwed up, & where you use to be able to see the servers activity (people logging on & off, chunks being loading) it is now a blank white section in the window. id' say for the time being until things progress, maybe take the easiest route in fixing problems like these

**Comment by goldbattle** [comment] 2015-01-24 18:13
I'll take a look into this.

**Comment by goldbattle** [comment] 2015-01-24 18:41
Please try deleting the `/assets/minecraft/textures/font/unicode_page_00.png`


![2015-01-24_13 41 19](https://cloud.githubusercontent.com/assets/2222562/5888500/ac46bd24-a3ce-11e4-90a1-ded11f665c71.png)
![2015-01-24_13 39 51](https://cloud.githubusercontent.com/assets/2222562/5888501/ac482c0e-a3ce-11e4-8b8e-cd5883fc9d2e.png)

**Comment by Oddface** [comment] 2015-01-24 19:28
That works out pretty well actually. It seems to keep the old John Smith font for everything except the mod books. Is the unicode file used for anything else? Looking at a few other resource packs and how they do fonts, I couldn't find any other pack that had unicode files. If all it does is mess up mod books, I would suggest removing it from all John Smith packs.

**Comment by goldbattle** [comment] 2015-01-24 20:28
Yeah, I just looked to what we were doing in both of our soartex packs.
Seems that it is just another option to have, and personally, the non-john
smith text in books is good for it.

This will be fixed on the next update.

On Sat, Jan 24, 2015 at 2:28 PM, Oddface <notifications@github.com> wrote:

> That works out pretty well actually. It seems to keep the old John Smith
> font for everything except the mod books. Is the unicode file used for
> anything else? Looking at a few other resource packs and how they do fonts,
> I couldn't find any other pack that had unicode files. If all it does is
> mess up mod books, I would suggest removing it from all John Smith packs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/John-Smith-Modded/JSTR-1.7.x/issues/51#issuecomment-71333418>
> .
>



-- 
Patrick Geneva | Administrator | pgb@soartex.net

**Comment by JokerReaper** [comment] 2015-01-25 08:18
thanks for that, its fixed, the floating text doesnt seems affected but i think that has to do with the mod & how it loads text from texture packs being used, minor problem but not a game breaker, anyways, im glad this was sorted i like this texture pack & frankly was tired of looking for one that i liked, ive tired way too many & seen this one in a youtube video, everyone did & is doing a great job, keep it up :+1:

**Comment by goldbattle** [comment] 2015-01-26 06:33
Should be good to go, latest download should have this all fixed. Thanks for the report!

**Comment by Oddface** [comment] 2015-02-23 12:31
If you use optifine or mcpatcher the font is still garbled in some of the books. The mcpatcher folder has a unicode file as well. When I removed that, it worked fine.

**Comment by goldbattle** [comment] 2015-02-23 14:23
File path?

**Comment by Oddface** [comment] 2015-02-23 14:44
assets\minecraft\mcpatcher\font\unicode_page_00.png

**Comment by goldbattle** [comment] 2015-02-23 18:10
Uploaded a new version, it should be good to go.
http://minecraft.curseforge.com/texture-packs/223328-john-smith-modded/files/2228505

**Comment by Oddface** [comment] 2015-02-23 21:59
The problem is fixed :+1:

**Closed by Oddface** 2015-02-23 21:59 UTC
Labels: bug, help wanted
